### ISSUE TITLE
Explainer revision

### ISSUE THREAD

**Issue by dhil** [wasmfx/specfx#3]
The explainer document could do with a revision.
* [x] Fix typos
* [x] Complete TODOs
* [x] Fix examples such that they no longer use deprecated features
* [x] Discuss effect forwarding upfront as it seems to be the more controversial feature
* [x] Sharpen up the overall narrative
* [x] Bring descriptions of the instruction set extension in sync with the reference implementation

**Comment by frank-emrich** [comment]
The descriptions of some instructions (notably: `resume` and `cont.bind`) are also slightly out of date, not showing all the required heap types that need to be given.

**Comment by dhil** [comment]
Partially addressed by #27.

**Comment by dhil** [comment]
In PR #30 I updated the control-lwt example such that it no longer uses `func.bind`.
